name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests-unix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: make test
      - name: Lint
        run: make lint
      - name: NanoVG build and test
        run: make -C nanovg test
      - name: Build examples
        run: make -C examples

  tests-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc make
      - name: Build and test
        shell: msys2 {0}
        run: make test
      - name: Lint
        shell: msys2 {0}
        run: make lint
      - name: NanoVG build and test
        shell: msys2 {0}
        run: make -C nanovg test
      - name: Build examples
        shell: msys2 {0}
        run: make -C examples
